services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      migrate:
        condition: service_started
    networks:
      - backend
  migrate:
    image: migrate/migrate
    networks:
      - backend
    volumes:
      - .:/config/migrations
    command:
      [
        "-path",
        "/config/migrations",
        "-database",
        "postgresql://master:SuperSecret123@postgres:5432/tickethub?sslmode=disable",
        "up"
      ]
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U master -d tickethub" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_DB: ${PG_DB}
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - pgdata:/var/lib/postgresql
    networks:
      - backend
volumes:
  pgdata:
networks:
  backend:
