basePath: /api/v1
definitions:
  dto.CreateEventOutputDTO:
    properties:
      address:
        type: string
      age_rating:
        type: integer
      date:
        type: string
      description:
        type: string
      genre_id:
        type: string
      id:
        type: string
      poster_url:
        type: string
      title:
        type: string
    type: object
  dto.CreateTicketInputDTO:
    properties:
      description:
        type: string
      event_id:
        type: string
      id:
        type: string
      max_per_user:
        type: integer
      name:
        type: string
      price:
        type: number
      total_qty:
        type: integer
    required:
    - description
    - event_id
    - max_per_user
    - name
    - price
    - total_qty
    type: object
  dto.CreateUserOutputDTO:
    properties:
      address:
        type: string
      cpf:
        type: string
      email:
        type: string
      id:
        type: string
      name:
        type: string
      surname:
        type: string
    type: object
  dto.GetManyEventsOutputDTO:
    properties:
      address:
        type: string
      created_at:
        type: string
      date:
        type: string
      genre:
        type: string
      id:
        type: string
      poster_url:
        type: string
      title:
        type: string
      updated_at:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:3000
info:
  contact: {}
  description: Serviço de ingressaria e tickets.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Tickethub
  version: "1.0"
paths:
  /event:
    get:
      description: Get events base on title search
      parameters:
      - description: Search
        in: query
        name: search
        required: true
        type: string
      - description: Limit
        in: query
        name: limit
        required: true
        type: integer
      - description: Page
        in: query
        name: page
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.GetManyEventsOutputDTO'
            type: array
        "406":
          description: Not Acceptable
        "500":
          description: Internal Server Error
      summary: Get many events
      tags:
      - event
    post:
      consumes:
      - application/json
      description: Create an show/event/festival/concert
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.CreateEventOutputDTO'
      summary: Create Event
      tags:
      - event
  /register:
    post:
      consumes:
      - application/json
      description: Create an account
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.CreateUserOutputDTO'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Register
      tags:
      - auth
  /ticket:
    post:
      consumes:
      - application/json
      description: Create an ticket
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.CreateTicketInputDTO'
      summary: Create ticket
      tags:
      - ticket
securityDefinitions:
  JWT:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
